name: go_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
    
jobs:
  build_and_tests:
    name: Test go_multi_log
    secrets: inherit
    with:
      go_version: ${{ vars.GO_VERSION }}
    uses: ./.github/workflows/w_tests.yml


