name: Release
# This workflow is triggered when a new tag is published
# `git tag v1.0.0`
# `git push --tags`
# If the tag already exists, use this commanf to delete it `git tag -d v1.0.0`
on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
    build_and_tests:
      name: Test go_multi_log
      secrets: inherit
      uses: ./.github/workflows/w_tests.yml
      with:
        go_version: 1.21
      
    release:
      if: contains(github.ref, 'tags/v')
      runs-on: ubuntu-latest
      needs: build_and_tests
      outputs: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        v_num:  ${{ steps.version.outputs.number }}
    
      steps:
        - uses: actions/checkout@v3
        - name: Get version number
          id: version
          run: |
            echo "number=$(echo '${{ github.ref }}' | cut -d '/' -f 3)" >>${GITHUB_OUTPUT}
        - name: Show version number
          run: |
            echo ${{ steps.version.outputs.number }}
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body_path: CHANGELOG.md
            draft: false
            prerelease: true   
        
    